# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
    # Inputs the workflow accepts.

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:

    - name: checkout
      uses: actions/checkout@v2

    - name: Copy php
      uses: garygrossgarten/github-action-scp@release
      with:
        local: php
        remote: /tmp/deploy/php
        host: ${{ secrets.CLOUD_SERVER }}
        username: ${{ secrets.CLOUD_USER }}
        password: ${{ secrets.CLOUD_USER_PASSWD }}

    - name: Copy Shell
      uses: garygrossgarten/github-action-scp@release
      with:
        local: sh
        remote: /tmp/deploy/sh
        host: ${{ secrets.CLOUD_SERVER }}
        username: ${{ secrets.CLOUD_USER }}
        password: ${{ secrets.CLOUD_USER_PASSWD }}
